# SPDX-License-Identifier: Apache-2.0
# Docker configuration for Fabric Orderer containers

version: "3"

networks:
  ecko:
    external:
      name: ecko-network

services:
  orderer0.eckochain.example.com:
    container_name: orderer0.eckochain.example.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LOCALMSPID=eckochain.example.com-MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/orderer0.eckochain.example.com-tlscert.crt
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/orderer0.eckochain.example.com-priv.key
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/orderer0.eckochain.example.com-tlscert.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/orderer0.eckochain.example.com-priv.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/orderer0.eckochain.example.com-tlscert.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/orderer0.eckochain.example.com-priv.key
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_FILELEDGER_LOCATION=/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
      - /eckostorage/fabric_data/crypto-config/orderer0.eckochain.example.com/enca/msp:/var/hyperledger/orderer/msp
      - /eckostorage/fabric_data/crypto-config/orderer0.eckochain.example.com/enca/tls:/var/hyperledger/orderer/tls
      - /eckostorage/fabric_data/production/orderer0.eckochain.example.com:/var/hyperledger/production/orderer
    ports:
      - 7050:7050
      - 7443:9443
    networks:
      - ecko
    command: orderer
    logging:
        driver: local

  orderer1.eckochain.example.com:
    container_name: orderer1.eckochain.example.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LOCALMSPID=eckochain.example.com-MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/orderer1.eckochain.example.com-tlscert.crt
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/orderer1.eckochain.example.com-priv.key
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/orderer1.eckochain.example.com-tlscert.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/orderer1.eckochain.example.com-priv.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/orderer1.eckochain.example.com-tlscert.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/orderer1.eckochain.example.com-priv.key
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_FILELEDGER_LOCATION=/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
      - /eckostorage/fabric_data/crypto-config/orderer1.eckochain.example.com/enca/msp:/var/hyperledger/orderer/msp
      - /eckostorage/fabric_data/crypto-config/orderer1.eckochain.example.com/enca/tls:/var/hyperledger/orderer/tls
      - /eckostorage/fabric_data/production/orderer1.eckochain.example.com:/var/hyperledger/production/orderer
    ports:
      - 8050:7050
      - 8443:9443
    networks:
      - ecko
    command: orderer
    logging:
        driver: local

  orderer2.eckochain.example.com:
    container_name: orderer2.eckochain.example.com
    image: hyperledger/fabric-orderer:2.3
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none
      - ORDERER_GENERAL_LOCALMSPID=eckochain.example.com-MSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/orderer2.eckochain.example.com-tlscert.crt
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/orderer2.eckochain.example.com-priv.key
      - ORDERER_GENERAL_TLS_ROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_GENERAL_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTCERTIFICATE=/var/hyperledger/orderer/tls/orderer2.eckochain.example.com-tlscert.crt
      - ORDERER_GENERAL_CLUSTER_CLIENTPRIVATEKEY=/var/hyperledger/orderer/tls/orderer2.eckochain.example.com-priv.key
      - ORDERER_GENERAL_CLUSTER_ROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/orderer2.eckochain.example.com-tlscert.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/orderer2.eckochain.example.com-priv.key
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=/var/hyperledger/orderer/msp/tlscacerts/tlsca.eckochain.example.com-cert.crt
      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:9443
      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_FILELEDGER_LOCATION=/var/hyperledger/production/orderer
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    volumes:
      - /eckostorage/fabric_data/crypto-config/orderer2.eckochain.example.com/enca/msp:/var/hyperledger/orderer/msp
      - /eckostorage/fabric_data/crypto-config/orderer2.eckochain.example.com/enca/tls:/var/hyperledger/orderer/tls
      - /eckostorage/fabric_data/production/orderer2.eckochain.example.com:/var/hyperledger/production/orderer
    ports:
      - 9050:7050
      - 9443:9443
    networks:
      - ecko
    command: orderer
    logging:
        driver: local
